
// This file is automatically generated, you probably don't want to edit this

'use strict';

module.exports = [{"name":"data","type":"Data","description":"The data set as a data frame\n"},{"name":"dep","title":"Dependent Variable","type":"Variable"},{"name":"ind","title":"Independent Variables","type":"Variables"}];
