
// This file is automatically generated, you probably don't want to edit this

'use strict';

module.exports = [{"name":"data","type":"Data"},{"name":"x","title":"x","type":"Variable"},{"name":"alternative","title":"alternative","type":"List","options":["two.sided","less","greater"],"default":"two.sided"},{"name":"mu","title":"mu","type":"Number","default":0},{"name":"confLevel","title":"conf.level","type":"Number","default":0.95}];
