
# This file is automatically generated, you probably don't want to edit this

AnovaOptions <- R6::R6Class(
    "AnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            ind = NULL, ...) {

            super$initialize(package='jmvbaseR', name='Anova', ...)
        
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..ind <- jmvcore::OptionVariables$new(
                "ind",
                ind)
        
            self$.addOption(private$..dep)
            self$.addOption(private$..ind)
        }),
    active = list(
        dep = function() private$..dep$value,
        ind = function() private$..ind$value),
    private = list(
        ..dep = NA,
        ..ind = NA)
)

AnovaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="ANOVA")}))

AnovaBase <- R6::R6Class(
    "AnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvbaseR',
                name = 'Anova',
                version = c(1,0,0),
                options = options,
                results = AnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

Anova <- function(
    data,
    dep,
    ind) {

    options <- AnovaOptions$new(
        dep = dep,
        ind = ind)

    results <- AnovaResults$new(
        options = options)

    analysis <- AnovaClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
