
# This file is automatically generated, you probably don't want to edit this

ttestISOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            grouping = NULL,
            alternative = "two.sided",
            mu = 0,
            varEqual = FALSE,
            confLevel = 0.95, ...) {

            super$initialize(
                package='jmvbaseR',
                name='ttestIS',
                requiresData=TRUE,
                ...)

            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent)
            private$..grouping <- jmvcore::OptionVariable$new(
                "grouping",
                grouping)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..varEqual <- jmvcore::OptionBool$new(
                "varEqual",
                varEqual,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95)

            self$.addOption(private$..dependent)
            self$.addOption(private$..grouping)
            self$.addOption(private$..alternative)
            self$.addOption(private$..mu)
            self$.addOption(private$..varEqual)
            self$.addOption(private$..confLevel)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        grouping = function() private$..grouping$value,
        alternative = function() private$..alternative$value,
        mu = function() private$..mu$value,
        varEqual = function() private$..varEqual$value,
        confLevel = function() private$..confLevel$value),
    private = list(
        ..dependent = NA,
        ..grouping = NA,
        ..alternative = NA,
        ..mu = NA,
        ..varEqual = NA,
        ..confLevel = NA)
)

ttestISResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples T-Test")}))

ttestISBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ttestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvbaseR',
                name = 'ttestIS',
                version = c(1,0,0),
                options = options,
                results = ttestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Independent Samples T-Test
#'
#' 
#' @param data the data as a data frame
#' @param dependent a string specifying the dependent variable in \code{data}
#' @param grouping a string specifying the grouping variable in \code{data};
#'   must have two levels
#' @param alternative \code{'two.sided'}, \code{'less'}, or \code{'greater'}
#' @param mu a number, the mean of the null hypothesis
#' @param varEqual TRUE or FALSE (default), assume equal variances
#' @param confLevel a number between 0 and 1 (default: 0.95), specifying the
#'   confidence interval width
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
ttestIS <- function(
    data,
    dependent,
    grouping,
    alternative = "two.sided",
    mu = 0,
    varEqual = FALSE,
    confLevel = 0.95) {

    if ( ! requireNamespace('jmvcore'))
        stop('ttestIS requires jmvcore to be installed (restart may be required)')

    options <- ttestISOptions$new(
        dependent = dependent,
        grouping = grouping,
        alternative = alternative,
        mu = mu,
        varEqual = varEqual,
        confLevel = confLevel)

    results <- ttestISResults$new(
        options = options)

    analysis <- ttestISClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
