
# This file is automatically generated, you probably don't want to edit this

TTestPSOptions <- R6::R6Class(
    "TTestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            alternative = "two.sided",
            mu = 0,
            varEqual = FALSE,
            confLevel = 0.95, ...) {

            super$initialize(package='jmvbaseR', name='TTestPS', ...)
        
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..varEqual <- jmvcore::OptionBool$new(
                "varEqual",
                varEqual,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95)
        
            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..alternative)
            self$.addOption(private$..mu)
            self$.addOption(private$..varEqual)
            self$.addOption(private$..confLevel)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        alternative = function() private$..alternative$value,
        mu = function() private$..mu$value,
        varEqual = function() private$..varEqual$value,
        confLevel = function() private$..confLevel$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..alternative = NA,
        ..mu = NA,
        ..varEqual = NA,
        ..confLevel = NA)
)

TTestPSResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Paired Samples T-Test")}))

TTestPSBase <- R6::R6Class(
    "TTestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvbaseR',
                name = 'TTestPS',
                version = c(1,0,0),
                options = options,
                results = TTestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

TTestPS <- function(
    data,
    x,
    y,
    alternative = "two.sided",
    mu = 0,
    varEqual = FALSE,
    confLevel = 0.95) {

    options <- TTestPSOptions$new(
        x = x,
        y = y,
        alternative = alternative,
        mu = mu,
        varEqual = varEqual,
        confLevel = confLevel)

    results <- TTestPSResults$new(
        options = options)

    analysis <- TTestPSClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
