
# This file is automatically generated, you probably don't want to edit this

TTestOneSOptions <- R6::R6Class(
    "TTestOneSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            alternative = "two.sided",
            mu = 0,
            confLevel = 0.95, ...) {

            super$initialize(package='jmvbaseR', name='TTestOneS', ...)
        
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95)
        
            self$.addOption(private$..x)
            self$.addOption(private$..alternative)
            self$.addOption(private$..mu)
            self$.addOption(private$..confLevel)
        }),
    active = list(
        x = function() private$..x$value,
        alternative = function() private$..alternative$value,
        mu = function() private$..mu$value,
        confLevel = function() private$..confLevel$value),
    private = list(
        ..x = NA,
        ..alternative = NA,
        ..mu = NA,
        ..confLevel = NA)
)

TTestOneSResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="One Sample T-Test")}))

TTestOneSBase <- R6::R6Class(
    "TTestOneSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvbaseR',
                name = 'TTestOneS',
                version = c(1,0,0),
                options = options,
                results = TTestOneSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

TTestOneS <- function(
    data,
    x,
    alternative = "two.sided",
    mu = 0,
    confLevel = 0.95) {

    options <- TTestOneSOptions$new(
        x = x,
        alternative = alternative,
        mu = mu,
        confLevel = confLevel)

    results <- TTestOneSResults$new(
        options = options)

    analysis <- TTestOneSClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
