
# This file is automatically generated, you probably don't want to edit this

TTestISOptions <- R6::R6Class(
    "TTestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dependent = NULL,
            grouping = NULL,
            alternative = "two.sided",
            mu = 0,
            varEqual = FALSE,
            confLevel = 0.95, ...) {

            super$initialize(package='jmvbaseR', name='TTestIS', ...)
        
            private$..dependent <- jmvcore::OptionVariable$new(
                "dependent",
                dependent)
            private$..grouping <- jmvcore::OptionVariable$new(
                "grouping",
                grouping)
            private$..alternative <- jmvcore::OptionList$new(
                "alternative",
                alternative,
                options=list(
                    "two.sided",
                    "less",
                    "greater"),
                default="two.sided")
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..varEqual <- jmvcore::OptionBool$new(
                "varEqual",
                varEqual,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                default=0.95)
        
            self$.addOption(private$..dependent)
            self$.addOption(private$..grouping)
            self$.addOption(private$..alternative)
            self$.addOption(private$..mu)
            self$.addOption(private$..varEqual)
            self$.addOption(private$..confLevel)
        }),
    active = list(
        dependent = function() private$..dependent$value,
        grouping = function() private$..grouping$value,
        alternative = function() private$..alternative$value,
        mu = function() private$..mu$value,
        varEqual = function() private$..varEqual$value,
        confLevel = function() private$..confLevel$value),
    private = list(
        ..dependent = NA,
        ..grouping = NA,
        ..alternative = NA,
        ..mu = NA,
        ..varEqual = NA,
        ..confLevel = NA)
)

TTestISResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Independent Samples T-Test")}))

TTestISBase <- R6::R6Class(
    "TTestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvbaseR',
                name = 'TTestIS',
                version = c(1,0,0),
                options = options,
                results = TTestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision)
        }))

TTestIS <- function(
    data,
    dependent,
    grouping,
    alternative = "two.sided",
    mu = 0,
    varEqual = FALSE,
    confLevel = 0.95) {

    options <- TTestISOptions$new(
        dependent = dependent,
        grouping = grouping,
        alternative = alternative,
        mu = mu,
        varEqual = varEqual,
        confLevel = confLevel)

    results <- TTestISResults$new(
        options = options)

    analysis <- TTestISClass$new(
        options = options,
        data = data)

    analysis$run()
    analysis$render()

    analysis
}
